#!/bin/sh

# TODO this should really be done in sbt

rm -rf ui/webstart/target/scala-2.9.2/webstart/
./sbt omath-ui-webstart/webstart
rsync -e ssh --partial --progress -avz ui/webstart/target/scala-2.9.2/webstart/* scottmorrison@omath.org:omath.org/webstart/
rsync -e ssh --partial --progress -avz ui/applet/src/main/html/* scottmorrison@omath.org:omath.org/webstart/
