/* Generated By:JJTree: Do not edit this line. ASTFullForm.java */

package org.omath.parser;

public class ASTFullForm extends FullFormNode {
	
	
  public ASTFullForm(int id) {
    super(id);
  }

  public ASTFullForm(SyntaxParser p, int id) {
    super(p, id);
  }
  
  
}
