/* Generated By:JJTree: Do not edit this line. ASTInequality.java */

package org.omath.parser;

public class ASTInequality extends InequalityNode {
  public ASTInequality(int id) {
    super(id);
  }

  public ASTInequality(SyntaxParserImpl p, int id) {
    super(p, id);
  }

}
