/* Generated By:JJTree: Do not edit this line. ASTStart.java */

package org.omath.parser;

public class ASTStart extends FullFormNode {
  public ASTStart(int id) {
    super(id);
  }

  public ASTStart(SyntaxParser p, int id) {
    super(p, id);
  }

}
