/* Generated By:JJTree: Do not edit this line. /Users/scott/projects/omath/parser/java-source/org/omath/parser/SyntaxParserTreeConstants.java */

package org.omath.parser;

 interface SyntaxParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTMYID = 2;
  public int JJTFULLFORM = 3;
  public int JJTINEQUALITY = 4;
  public int JJTMYINTEGER = 5;
  public int JJTPLUSTERM = 6;
  public int JJTOPTIONAL = 7;
  public int JJTMYSTRING = 8;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "MyID",
    "FullForm",
    "Inequality",
    "MyInteger",
    "PlusTerm",
    "Optional",
    "MyString",
  };
}
